import type { HtmlElementInfo } from './types';

// Element data sourced from the WHATWG HTML Living Standard elements index:
// each element's content categories, content model (children), and contexts
// (parents) in structured form. Generated with tooling assistance and
// corrected by hand. See HTML_ELEMENT_TAGS for the list of covered tags.
export const HTML_ELEMENTS: readonly HtmlElementInfo[] = [
  {
    tag: 'a',
    description: 'Anchor element representing a hyperlink',
    categories: ['flow', 'phrasing', 'palpable'],
    conditionalCategories: ['interactive'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      excludedCategories: ['interactive'],
      excludedElements: ['a'],
      note: "Follows the parent's content model. Must not contain interactive content, a elements, or elements with a tabindex attribute among its descendants",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'abbr',
    description: 'Abbreviation or acronym',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'address',
    description: 'Contact information',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedCategories: ['heading', 'sectioning'],
      excludedElements: ['header', 'footer', 'address'],
      note: 'Must not contain heading content, sectioning content, header, footer, or address descendants',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'area',
    description: 'Region on an image map',
    categories: [],
    conditionalCategories: ['flow', 'phrasing'],
    conditionalNote: 'Only if there is a map element ancestor',
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: [],
      conditionalElements: ['map'],
      note: 'Must be a descendant of a map element',
    },
    void: true,
  },
  {
    tag: 'article',
    description: 'Self-contained, independently distributable composition',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'aside',
    description: 'Content tangentially related to the surrounding content',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'audio',
    description: 'Embedded sound or audio stream',
    categories: ['flow', 'phrasing', 'embedded'],
    conditionalCategories: ['interactive', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['source', 'track'],
      excludedElements: ['audio', 'video'],
      note: "Follows the parent's content model. If there is no src attribute: source elements, then track elements; must not contain media element descendants",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'b',
    description: 'Text to which attention is being drawn',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'base',
    description: 'Base URL and default link target for the document',
    categories: ['metadata'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['head'] },
    void: true,
  },
  {
    tag: 'bdi',
    description: 'Text isolated for bidirectional formatting',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'bdo',
    description: 'Explicit text directionality override',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'blockquote',
    description: 'Section quoted from another source',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'body',
    description: 'Main content of the document, directly under the root',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['html'],
      note: 'Second child of the html element',
    },
    void: false,
  },
  {
    tag: 'br',
    description: 'Line break',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'button',
    description: 'Clickable button',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: ['listed', 'labelable', 'submittable', 'form-associated'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedCategories: ['interactive'],
      note: 'Phrasing content with no interactive content descendants',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'canvas',
    description: 'Scriptable resolution-dependent bitmap canvas',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: "Follows the parent's content model (transparent). Fallback content may include interactive and form elements",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'caption',
    description: 'Title or caption of a table',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['table'],
      note: 'Flow content with no table element descendants',
    },
    contexts: {
      categories: [],
      elements: ['table'],
      note: 'First child of a table element',
    },
    void: false,
  },
  {
    tag: 'cite',
    description: 'Title of a work',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'code',
    description: 'Fragment of computer code',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'col',
    description: 'Table column',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['colgroup'],
      note: 'Child of a colgroup element that has no span attribute',
    },
    void: true,
  },
  {
    tag: 'colgroup',
    description: 'Group of table columns',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: [],
      conditionalElements: ['col', 'template'],
      note: 'When it has no span attribute: col and template elements',
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'data',
    description: 'Content with a machine-readable value',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'datalist',
    description: 'Predefined options for other controls',
    categories: ['flow', 'phrasing'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      conditionalCategories: ['script-supporting'],
      conditionalElements: ['option'],
      note: 'Either phrasing content, or option elements mixed with script-supporting elements',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'dd',
    description: 'Description or value in a description list',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['dl', 'div'],
      note: 'Inside a dl element, or inside a div child of a dl element',
    },
    void: false,
  },
  {
    tag: 'del',
    description: 'Content removed from the document',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: "Follows the parent's content model",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'details',
    description: 'Disclosure widget that can be opened and closed',
    categories: ['flow', 'interactive', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['summary'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'dfn',
    description: 'Defining instance of a term',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['dfn'],
      note: 'Phrasing content with no dfn element descendants',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'dialog',
    description: 'Dialog box or subwindow',
    categories: ['flow'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'div',
    description: 'Generic block-level container',
    categories: [
      'flow',
      'palpable',
      'select-inner',
      'optgroup-inner',
      'option-inner',
    ],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      conditionalCategories: ['select-inner', 'optgroup-inner', 'option-inner'],
    },
    contexts: {
      categories: ['flow', 'select-inner', 'optgroup-inner', 'option-inner'],
      elements: ['dl'],
    },
    void: false,
  },
  {
    tag: 'dl',
    description: 'Description list of name-value groups',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['dt', 'dd', 'div'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'dt',
    description: 'Name or term in a description list',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedCategories: ['heading', 'sectioning'],
      excludedElements: ['header', 'footer'],
      note: 'Flow content with no header, footer, sectioning content, or heading content descendants',
    },
    contexts: {
      categories: [],
      elements: ['dl', 'div'],
    },
    void: false,
  },
  {
    tag: 'em',
    description: 'Stress emphasis',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'embed',
    description: 'Integration point for an external application or plugin',
    categories: ['flow', 'phrasing', 'embedded', 'interactive', 'palpable'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'fieldset',
    description: 'Group of form controls',
    categories: ['flow', 'palpable'],
    formCategories: ['listed', 'form-associated'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['legend'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'figcaption',
    description: 'Caption or legend for a figure',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['figure'] },
    void: false,
  },
  {
    tag: 'figure',
    description: 'Self-contained content with an optional caption',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['figcaption'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'footer',
    description:
      'Footer for its section: authorship, related links, and similar',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['header', 'footer'],
      note: 'Must not contain header or footer descendants',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'form',
    description: 'Form with submittable controls',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['form'],
      note: 'Must not contain form element descendants',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'h1',
    description: 'Heading level 1 (highest)',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h2',
    description: 'Heading level 2',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h3',
    description: 'Heading level 3',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h4',
    description: 'Heading level 4',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h5',
    description: 'Heading level 5',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h6',
    description: 'Heading level 6 (lowest)',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'head',
    description: 'Container for document metadata',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['metadata'],
      elements: [],
    },
    contexts: { categories: [], elements: ['html'] },
    void: false,
  },
  {
    tag: 'header',
    description: 'Introductory content or navigation aids for its section',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['header', 'footer'],
      note: 'Must not contain header or footer descendants',
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'hgroup',
    description: 'Heading grouped with subheadings',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p'],
    },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'hr',
    description: 'Paragraph-level thematic break',
    categories: ['flow', 'select-inner'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['flow', 'select-inner'], elements: [] },
    void: true,
  },
  {
    tag: 'html',
    description: 'Root element of an HTML document; contains head and body',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: ['head', 'body'],
    },
    contexts: {
      categories: [],
      elements: [],
      special: 'root',
      note: 'Root element',
    },
    void: false,
  },
  {
    tag: 'i',
    description: 'Text in an alternate voice or mood (idiomatic text)',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'iframe',
    description: 'Nested browsing context (inline frame)',
    categories: ['flow', 'phrasing', 'embedded', 'interactive', 'palpable'],
    contentModel: {
      kind: 'none',
      categories: [],
      elements: [],
      note: 'Nothing; iframe is not a void element and requires an end tag',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'img',
    description: 'Embedded image',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    formCategories: ['form-associated'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: ['picture'] },
    void: true,
  },
  {
    tag: 'input',
    description: 'Form input control',
    categories: ['flow', 'phrasing'],
    conditionalCategories: ['interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'ins',
    description: 'Content added to the document',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: "Follows the parent's content model",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'kbd',
    description: 'User input, such as keyboard input',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'label',
    description: 'Caption for a form control',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['label'],
      note: 'Phrasing content with no label element descendants',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'legend',
    description: 'Caption for a fieldset',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing', 'heading'],
      elements: [],
    },
    contexts: { categories: [], elements: ['fieldset', 'optgroup'] },
    void: false,
  },
  {
    tag: 'li',
    description: 'List item',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['ol', 'ul', 'menu'],
    },
    void: false,
  },
  {
    tag: 'link',
    description: 'Link to an external resource (metadata)',
    categories: ['metadata'],
    conditionalCategories: ['flow', 'phrasing'],
    conditionalNote:
      'When it has an itemprop attribute, or rel consists only of body-ok keywords (stylesheet, preload, preconnect, ...); it may then appear in the body',
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: true,
  },
  {
    tag: 'main',
    description: 'Dominant content of the document',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'map',
    description: 'Image map definition with clickable areas',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['area'],
      note: "Follows the parent's content model. May contain area element descendants",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'mark',
    description: 'Text highlighted for reference or notation',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'math',
    description: 'Root of a MathML mathematical expression',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'foreign',
      categories: [],
      elements: [],
      note: 'MathML foreign content',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'menu',
    description: 'Toolbar-like list of commands',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'meta',
    description: 'Document metadata',
    categories: ['metadata'],
    conditionalCategories: ['flow', 'phrasing'],
    conditionalNote:
      'When it has an itemprop attribute (microdata); it may then appear in the body',
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
      note: 'Inside noscript, or in phrasing contexts in some cases',
    },
    void: true,
  },
  {
    tag: 'meter',
    description: 'Gauge for a scalar value within a known range',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['labelable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['meter'],
      note: 'Phrasing content with no meter element descendants',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'nav',
    description: 'Section of navigation links',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'noscript',
    description: 'Fallback content for when scripting is disabled',
    categories: [
      'metadata',
      'flow',
      'phrasing',
      'select-inner',
      'optgroup-inner',
    ],
    contentModel: {
      kind: 'varies',
      categories: [],
      elements: [],
      note: 'Varies by context (differs depending on whether scripting is enabled)',
    },
    contexts: {
      categories: [],
      elements: [],
      conditionalElements: ['head'],
      note: 'Inside head, or in phrasing contexts in some cases',
    },
    void: false,
  },
  {
    tag: 'object',
    description: 'External resource such as an image or nested document',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    formCategories: ['listed', 'form-associated'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: "Follows the parent's content model",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'ol',
    description: 'Ordered list',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'optgroup',
    description: 'Group of options inside a select',
    categories: ['select-inner'],
    contentModel: {
      kind: 'elements',
      categories: ['optgroup-inner', 'script-supporting'],
      elements: ['legend'],
    },
    contexts: {
      categories: [],
      elements: ['select'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'option',
    description: 'Option in a select, datalist, or optgroup',
    categories: ['select-inner', 'optgroup-inner'],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      conditionalCategories: ['option-inner'],
      note: 'Text, or option element inner content in customizable select elements',
    },
    contexts: {
      categories: [],
      elements: ['select', 'datalist', 'optgroup'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'output',
    description: 'Result of a calculation',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['listed', 'labelable', 'resettable', 'form-associated'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'p',
    description: 'Paragraph',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'picture',
    description: 'Container offering multiple image sources',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['source', 'img'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'pre',
    description: 'Preformatted text',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'progress',
    description: 'Progress of a task',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['labelable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['progress'],
      note: 'Phrasing content with no progress element descendants',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'q',
    description: 'Short inline quotation',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'rp',
    description: 'Fallback parentheses for browsers without ruby support',
    categories: [],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: [], elements: ['ruby'] },
    void: false,
  },
  {
    tag: 'rt',
    description: 'Ruby text annotation',
    categories: [],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: [], elements: ['ruby'] },
    void: false,
  },
  {
    tag: 'ruby',
    description: 'Ruby annotation',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: ['rt', 'rp'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 's',
    description: 'Content that is no longer accurate (strikethrough)',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'samp',
    description: 'Sample output from a program',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'script',
    description: 'Embedded script or data',
    categories: ['metadata', 'flow', 'phrasing', 'script-supporting'],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      note: 'Script such as JavaScript, or data',
    },
    contexts: {
      categories: ['phrasing', 'script-supporting'],
      elements: ['head'],
    },
    void: false,
  },
  {
    tag: 'search',
    description: 'Region for search or filtering controls',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'section',
    description: 'Generic section with a heading',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'select',
    description: 'Control for selecting among options',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: {
      kind: 'elements',
      categories: ['select-inner', 'script-supporting'],
      elements: [],
      conditionalElements: ['button'],
      note: 'In a customizable select, a single button may appear first',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'selectedcontent',
    description: 'Mirror of the selected option content inside a select',
    categories: [],
    contentModel: {
      kind: 'none',
      categories: [],
      elements: [],
      note: 'Nothing; the browser mirrors the selected option content into it',
    },
    contexts: { categories: [], elements: ['button'] },
    void: false,
  },
  {
    tag: 'slot',
    description: 'Placeholder for shadow DOM content',
    categories: ['flow', 'phrasing'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      note: "Follows the parent's content model. May hold fallback content",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'small',
    description: 'Side comment such as a disclaimer or fine print',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'source',
    description: 'Media source candidate for picture, video, or audio',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['picture', 'video', 'audio'] },
    void: true,
  },
  {
    tag: 'span',
    description: 'Generic inline container with no inherent meaning',
    categories: ['flow', 'phrasing', 'palpable'],
    conditionalCategories: ['option-inner'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'strong',
    description: 'Strong importance or urgency',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'style',
    description: 'Embedded CSS style information',
    categories: ['metadata'],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      note: 'Style information such as CSS',
    },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: false,
  },
  {
    tag: 'sub',
    description: 'Subscript',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'summary',
    description: 'Summary or caption for a details disclosure',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing', 'heading'],
      elements: [],
    },
    contexts: { categories: [], elements: ['details'] },
    void: false,
  },
  {
    tag: 'sup',
    description: 'Superscript',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'svg',
    description: 'Embedded SVG vector graphics',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'foreign',
      categories: [],
      elements: [],
      note: 'SVG foreign content',
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'table',
    description: 'Tabular data',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['caption', 'colgroup', 'thead', 'tbody', 'tfoot', 'tr'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'tbody',
    description: 'Group of table body rows',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'td',
    description: 'Table data cell',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['tr'] },
    void: false,
  },
  {
    tag: 'template',
    description: 'Template for client-side content cloning',
    categories: ['metadata', 'flow', 'phrasing', 'script-supporting'],
    contentModel: {
      kind: 'none',
      categories: [],
      elements: [],
      note: 'Content model is Nothing; its markup is stored in the content DocumentFragment',
    },
    contexts: {
      categories: ['metadata', 'phrasing', 'script-supporting'],
      elements: [],
      conditionalElements: ['colgroup'],
    },
    void: false,
  },
  {
    tag: 'textarea',
    description: 'Multiline plain-text form control',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'tfoot',
    description: 'Group of table footer rows',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'th',
    description: 'Table header cell',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedCategories: ['heading', 'sectioning'],
      excludedElements: ['header', 'footer'],
      note: 'Flow content with no heading, sectioning, header, or footer descendants',
    },
    contexts: { categories: [], elements: ['tr'] },
    void: false,
  },
  {
    tag: 'thead',
    description: 'Group of table header rows',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'time',
    description: 'Machine-readable date, time, or duration',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'title',
    description: 'Document title (metadata)',
    categories: ['metadata'],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: [], elements: ['head'] },
    void: false,
  },
  {
    tag: 'tr',
    description: 'Table row of cells (th / td)',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['td', 'th', 'script', 'template'],
      note: 'Cells (td / th) and script-supporting elements',
    },
    contexts: {
      categories: [],
      elements: ['table', 'thead', 'tbody', 'tfoot'],
    },
    void: false,
  },
  {
    tag: 'track',
    description: 'Timed text track (captions, subtitles) for media elements',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['audio', 'video'] },
    void: true,
  },
  {
    tag: 'u',
    description: 'Text with a non-textual annotation (unarticulated)',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'ul',
    description: 'Unordered list',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li', 'script', 'template'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'var',
    description: 'Variable in a mathematical expression or program',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'video',
    description: 'Embedded video',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['source', 'track'],
      excludedElements: ['audio', 'video'],
      note: "Follows the parent's content model. If there is no src attribute, source elements may appear (track elements may appear either way)",
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'wbr',
    description: 'Line-break opportunity',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
];

// Every tag name in the dataset, in order of appearance (near-alphabetical).
export const HTML_ELEMENT_TAGS: readonly string[] = HTML_ELEMENTS.map(
  (element) => element.tag,
);
