import type { ElementDescription, HtmlElementInfo } from './types';

// Element data sourced from the WHATWG HTML Living Standard elements index:
// each element's content categories, content model (children), and contexts
// (parents) in structured form. Generated with tooling assistance and
// corrected by hand. See HTML_ELEMENT_TAGS for the list of covered tags.
//
// Structure only: the English display strings (description and the note
// fields) live in ./descriptions and are merged in with
// applyElementDescriptions, so bundles that localize or never render them
// do not ship them.
export const HTML_ELEMENTS: readonly HtmlElementInfo[] = [
  {
    tag: 'a',
    categories: ['flow', 'phrasing', 'palpable'],
    conditionalCategories: ['interactive'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      excludedCategories: ['interactive'],
      excludedElements: ['a'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'abbr',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'address',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedCategories: ['heading', 'sectioning'],
      excludedElements: ['header', 'footer', 'address'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'area',
    categories: [],
    conditionalCategories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: [], conditionalElements: ['map'] },
    void: true,
  },
  {
    tag: 'article',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'aside',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'audio',
    categories: ['flow', 'phrasing', 'embedded'],
    conditionalCategories: ['interactive', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['track'],
      conditionalElements: ['source'],
      excludedElements: ['audio', 'video'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'b',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'base',
    categories: ['metadata'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['head'] },
    void: true,
  },
  {
    tag: 'bdi',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'bdo',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'blockquote',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'body',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['html'] },
    void: false,
  },
  {
    tag: 'br',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'button',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: ['listed', 'labelable', 'submittable', 'form-associated'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedCategories: ['interactive'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'canvas',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: [],
      excludedElements: ['details', 'embed', 'iframe', 'label', 'textarea'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'caption',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['table'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'cite',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'code',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'col',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: [],
      conditionalElements: ['colgroup'],
    },
    void: true,
  },
  {
    tag: 'colgroup',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: [],
      conditionalElements: ['col', 'template'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'data',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'datalist',
    categories: ['flow', 'phrasing'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      conditionalCategories: ['script-supporting'],
      conditionalElements: ['option'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'dd',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: {
      categories: [],
      elements: ['dl'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'del',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'transparent', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'details',
    categories: ['flow', 'interactive', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['summary'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'dfn',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['dfn'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'dialog',
    categories: ['flow'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'div',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: ['dl'] },
    void: false,
  },
  {
    tag: 'dl',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['dt', 'dd', 'div'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'dt',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedCategories: ['heading', 'sectioning'],
      excludedElements: ['header', 'footer'],
    },
    contexts: {
      categories: [],
      elements: ['dl'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'em',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'embed',
    categories: ['flow', 'phrasing', 'embedded', 'interactive', 'palpable'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'fieldset',
    categories: ['flow', 'palpable'],
    formCategories: ['listed', 'form-associated'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['legend'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'figcaption',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['figure'] },
    void: false,
  },
  {
    tag: 'figure',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: ['figcaption'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'footer',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['header', 'footer'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'form',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['form'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'h1',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h2',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h3',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h4',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h5',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'h6',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'head',
    categories: [],
    contentModel: { kind: 'elements', categories: ['metadata'], elements: [] },
    contexts: { categories: [], elements: ['html'] },
    void: false,
  },
  {
    tag: 'header',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedElements: ['header', 'footer'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'hgroup',
    categories: ['flow', 'heading', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p'],
    },
    contexts: { categories: ['flow'], elements: ['legend', 'summary'] },
    void: false,
  },
  {
    tag: 'hr',
    categories: ['flow'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: true,
  },
  {
    tag: 'html',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: [],
      elements: ['head', 'body'],
    },
    contexts: { categories: [], elements: [], special: 'root' },
    void: false,
  },
  {
    tag: 'i',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'iframe',
    categories: ['flow', 'phrasing', 'embedded', 'interactive', 'palpable'],
    contentModel: { kind: 'none', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'img',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    formCategories: ['form-associated'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: ['picture'] },
    void: true,
  },
  {
    tag: 'input',
    categories: ['flow', 'phrasing'],
    conditionalCategories: ['interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
  {
    tag: 'ins',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'transparent', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'kbd',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'label',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['label'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'legend',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing', 'heading'],
      elements: [],
    },
    contexts: { categories: [], elements: ['fieldset', 'optgroup'] },
    void: false,
  },
  {
    tag: 'li',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['ol', 'ul', 'menu'] },
    void: false,
  },
  {
    tag: 'link',
    categories: ['metadata'],
    conditionalCategories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: true,
  },
  {
    tag: 'main',
    categories: ['palpable'],
    conditionalCategories: ['flow'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'map',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'transparent', categories: [], elements: ['area'] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'mark',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'math',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: { kind: 'foreign', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'menu',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'meta',
    categories: ['metadata'],
    conditionalCategories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: true,
  },
  {
    tag: 'meter',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['labelable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['meter'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'nav',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'noscript',
    categories: ['metadata', 'flow', 'phrasing'],
    contentModel: {
      kind: 'varies',
      categories: [],
      elements: [],
      conditionalCategories: ['flow', 'phrasing'],
      excludedElements: ['noscript'],
    },
    contexts: { categories: [], elements: [], conditionalElements: ['head'] },
    void: false,
  },
  {
    tag: 'object',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    formCategories: ['listed', 'form-associated'],
    contentModel: { kind: 'transparent', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'ol',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'optgroup',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['legend', 'option', 'noscript', 'div'],
    },
    contexts: {
      categories: [],
      elements: ['select'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'option',
    categories: [],
    contentModel: {
      kind: 'text',
      categories: [],
      elements: [],
      conditionalCategories: ['phrasing'],
      conditionalElements: ['div'],
      excludedCategories: ['interactive'],
      excludedElements: ['datalist', 'object'],
    },
    contexts: {
      categories: [],
      elements: ['select', 'datalist', 'optgroup'],
      conditionalElements: ['div'],
    },
    void: false,
  },
  {
    tag: 'output',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['listed', 'labelable', 'resettable', 'form-associated'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'p',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'picture',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['source', 'img'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'pre',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'progress',
    categories: ['flow', 'phrasing', 'palpable'],
    formCategories: ['labelable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: [],
      excludedElements: ['progress'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'q',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'rp',
    categories: [],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: [], elements: ['ruby'] },
    void: false,
  },
  {
    tag: 'rt',
    categories: [],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: [], elements: ['ruby'] },
    void: false,
  },
  {
    tag: 'ruby',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing'],
      elements: ['rt', 'rp'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 's',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'samp',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'script',
    categories: ['metadata', 'flow', 'phrasing', 'script-supporting'],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: {
      categories: ['phrasing', 'script-supporting'],
      elements: ['head'],
    },
    void: false,
  },
  {
    tag: 'search',
    categories: ['flow', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'section',
    categories: ['flow', 'sectioning', 'palpable'],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'select',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['option', 'optgroup', 'hr', 'noscript', 'div'],
      conditionalElements: ['button'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'selectedcontent',
    categories: [],
    conditionalCategories: ['phrasing'],
    contentModel: { kind: 'none', categories: [], elements: [] },
    contexts: { categories: [], elements: [], conditionalElements: ['button'] },
    void: false,
  },
  {
    tag: 'slot',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'transparent', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'small',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'source',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['picture', 'video', 'audio'] },
    void: true,
  },
  {
    tag: 'span',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'strong',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'style',
    categories: ['metadata'],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: {
      categories: [],
      elements: ['head'],
      conditionalElements: ['noscript'],
    },
    void: false,
  },
  {
    tag: 'sub',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'summary',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['phrasing', 'heading'],
      elements: [],
    },
    contexts: { categories: [], elements: ['details'] },
    void: false,
  },
  {
    tag: 'sup',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'svg',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    contentModel: { kind: 'foreign', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'table',
    categories: ['flow', 'palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['caption', 'colgroup', 'thead', 'tbody', 'tfoot'],
      conditionalElements: ['tr'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'tbody',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'td',
    categories: [],
    contentModel: { kind: 'elements', categories: ['flow'], elements: [] },
    contexts: { categories: [], elements: ['tr'] },
    void: false,
  },
  {
    tag: 'template',
    categories: ['metadata', 'flow', 'phrasing', 'script-supporting'],
    contentModel: { kind: 'none', categories: [], elements: [] },
    contexts: {
      categories: ['metadata', 'phrasing', 'script-supporting'],
      elements: [],
      conditionalElements: ['colgroup'],
    },
    void: false,
  },
  {
    tag: 'textarea',
    categories: ['flow', 'phrasing', 'interactive', 'palpable'],
    formCategories: [
      'listed',
      'labelable',
      'submittable',
      'resettable',
      'form-associated',
    ],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'tfoot',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'th',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['flow'],
      elements: [],
      excludedCategories: ['heading', 'sectioning'],
      excludedElements: ['header', 'footer'],
    },
    contexts: { categories: [], elements: ['tr'] },
    void: false,
  },
  {
    tag: 'thead',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['tr'],
    },
    contexts: { categories: [], elements: ['table'] },
    void: false,
  },
  {
    tag: 'time',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'title',
    categories: ['metadata'],
    contentModel: { kind: 'text', categories: [], elements: [] },
    contexts: { categories: [], elements: ['head'] },
    void: false,
  },
  {
    tag: 'tr',
    categories: [],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['td', 'th', 'script', 'template'],
    },
    contexts: {
      categories: [],
      elements: ['thead', 'tbody', 'tfoot'],
      conditionalElements: ['table'],
    },
    void: false,
  },
  {
    tag: 'track',
    categories: [],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: [], elements: ['audio', 'video'] },
    void: true,
  },
  {
    tag: 'u',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'ul',
    categories: ['flow'],
    conditionalCategories: ['palpable'],
    contentModel: {
      kind: 'elements',
      categories: ['script-supporting'],
      elements: ['li', 'script', 'template'],
    },
    contexts: { categories: ['flow'], elements: [] },
    void: false,
  },
  {
    tag: 'var',
    categories: ['flow', 'phrasing', 'palpable'],
    contentModel: { kind: 'elements', categories: ['phrasing'], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'video',
    categories: ['flow', 'phrasing', 'embedded', 'palpable'],
    conditionalCategories: ['interactive'],
    contentModel: {
      kind: 'transparent',
      categories: [],
      elements: ['track'],
      conditionalElements: ['source'],
      excludedElements: ['audio', 'video'],
    },
    contexts: { categories: ['phrasing'], elements: [] },
    void: false,
  },
  {
    tag: 'wbr',
    categories: ['flow', 'phrasing'],
    contentModel: { kind: 'empty', categories: [], elements: [] },
    contexts: { categories: ['phrasing'], elements: [] },
    void: true,
  },
];

// Every tag name in the dataset, in order of appearance (near-alphabetical).
export const HTML_ELEMENT_TAGS: readonly string[] = HTML_ELEMENTS.map(
  (element) => element.tag,
);

// Merge display strings into structure-only element data. Works with any
// per-tag record of the ElementDescription shape, so localized strings can
// be applied the same way as the bundled English ones (./descriptions).
// Elements whose tag is missing from the record are returned unchanged.
export const applyElementDescriptions = (
  elements: readonly HtmlElementInfo[],
  descriptions: Readonly<Record<string, ElementDescription>>,
): HtmlElementInfo[] =>
  elements.map((element) => {
    const entry = descriptions[element.tag];
    if (entry === undefined) {
      return element;
    }
    // Attach optional fields conditionally to stay compatible with
    // exactOptionalPropertyTypes.
    return {
      ...element,
      description: entry.description,
      ...(entry.conditionalNote === undefined
        ? {}
        : { conditionalNote: entry.conditionalNote }),
      contentModel:
        entry.contentModelNote === undefined
          ? element.contentModel
          : { ...element.contentModel, note: entry.contentModelNote },
      contexts:
        entry.contextsNote === undefined
          ? element.contexts
          : { ...element.contexts, note: entry.contextsNote },
    };
  });
