name: Pavo

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  pavo:
    if: ${{ github.event_name != 'issue_comment' || startsWith(github.event.comment.body, '/pavo') }}
    uses: k35o/pavo/.github/workflows/review.yml@1f137410e46b7d9559763b34b9647087f3c5b07f # main
    with:
      instructions: default,typescript
    secrets: inherit
